# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_category_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='blogs.Category'),
        ),
    ]
